aws_region      = "ap-south-1"
environment     = "dev"
vpc_cidr        = "10.0.0.0/16"
instance_type   = "t2.micro"
ami_id          = "ami-0f58b397bc5c1f2e8"
bucket_name     = "my-terraform-dev-bucket-omkar"
public_key_path = "~/.ssh/id_rsa.pub"
